DATA:
  data_name: s3dis
  data_root: data/s3dis/trainval_fullarea
  classes: 13
  aug: True
  voxelSize: 0.05
  voxel_max: 80000
  test_area: 5

TRAIN:
  arch: retro_fpn
  ignore_label: 255
  train_gpu:  [0, 1, 2, 3] #
  workers: 16 # data loader workers
  batch_size: 16 # batch size for training
  batch_size_val: 8 # batch size for validation during training, memory and speed add
  base_lr: 0.1
  loop: 10
  epochs: 100
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed: 1463
  print_freq: 10
  save_freq: 1
  save_path: exp/s3dis/retrofpn 
  weight:  # path to initial weight (default: none)
  resume: 
  evaluate: True  
  eval_freq: 1

Model:
  n_samples: 12  # knn
  plane_share: 8
  plane_cls: 32
  strides: [1, 1, 1, 1, 1]

Distributed:
  dist_url: tcp://127.0.0.1:6788
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  split: val  # split in [train, val and test]
  val_benchmark: True
  test_workers: 4
  test_gpu: [0, 1, 2, 3]
  test_batch_size: 4
  model_path: checkpoints/s3dis_retrofpn.pth.tar
  save_folder: exp/s3dis/retrofpn
  test_repeats: 7